/*
 * $Id: SwingMain.java 281 2005-01-12 07:56:44Z wadechandler $
 *
 * Copyright 2004 Sun Microsystems, Inc., 4150 Network Circle,
 * Santa Clara, California 95054, U.S.A. All rights reserved.
 */

/*
 * SwingMain.java
 *
 * Created on January 12, 2005, 12:40 AM
 */

package org.jdesktop.jdnc.incubator.wadechandler;

import org.jdesktop.jdnc.incubator.wadechandler.swing.box.BoxFillerDemo;

/**
 *
 * @author  wchan
 */
public class SwingMain extends javax.swing.JFrame {
    
    /** Creates new form SwingMain */
    public SwingMain() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        buttonBoxFiller = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jLabel1.setText("This launches the other demos");
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        buttonBoxFiller.setText("BoxFiller");
        buttonBoxFiller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBoxFillerActionPerformed(evt);
            }
        });

        jPanel1.add(buttonBoxFiller);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void buttonBoxFillerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBoxFillerActionPerformed
        BoxFillerDemo demo = new BoxFillerDemo();
        demo.setVisible(true);
    }//GEN-LAST:event_buttonBoxFillerActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SwingMain().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBoxFiller;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
