######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 22 14:34:40 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += declarative
CONFIG += debug

include(../examples.pri)

# Input
HEADERS += creator.h
SOURCES += creator.cpp main.cpp
