import java.awt.GridBagConstraints;
import java.awt.event.MouseAdapter;
import javax.swing.JComponent;
import org.jdesktop.swingx.JXStatusBeanBar;
import org.jdesktop.swingx.statusbar.JXMemoryStatusBean;
import org.jdesktop.swingx.statusbar.JXClockStatusBean;
import org.jdesktop.swingx.statusbar.JXMessageStatusBean;
import org.jdesktop.swingx.statusbar.sample.SampleDownloadStatusBean;


/**
 *
 * @author  patrick
 */
public class StatusFrameControl extends javax.swing.JPanel {
    private StatusFrameDemo frame;
    // a clock
    JXClockStatusBean clock;
    
    // an "elapsed time" bean
    JXClockStatusBean elapsedTime;
    
    // an "free memory" bean
    JXMemoryStatusBean memory;
    
    // a message display
    JXMessageStatusBean message;;
    
    // a bean to tell the user a download is available
    SampleDownloadStatusBean download;
    
    
    /** Creates new form StatusFrameControl */
    public StatusFrameControl(StatusFrameDemo frame) {
        initComponents();
        // the status bar for all our components
        JXStatusBeanBar statusBar = new JXStatusBeanBar();
        
        // a clock
        clock = new JXClockStatusBean();
        
        // an "elapsed time" bean
        elapsedTime = JXClockStatusBean.newElapsedTimeBean(100, "mm:ss:SSSS");
        elapsedTime.stopClock();
        elapsedTime.getDisplayComponent().setVisible(false);
        
        // an "free memory" bean
        memory = new JXMemoryStatusBean();
        
        // a message display
        message = new JXMessageStatusBean();
        
        download = new SampleDownloadStatusBean();
        download.getDisplayComponent().setVisible(false);
        
        statusBar.addStatusBean(message);
        statusBar.addStatusBean(memory);
        statusBar.addStatusBean(elapsedTime, 0D, GridBagConstraints.EAST);
        statusBar.addStatusBean(clock, 0D, GridBagConstraints.EAST);
        statusBar.addStatusBean(download, 0D, GridBagConstraints.EAST);
        
        
        // TODO: this is built in somehow to the current JXStatusBar
        MouseAdapter tooltipAdapter = new MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent e) {
                if ( e.getComponent() instanceof JComponent ) {
                    String text = ((JComponent)e.getComponent()).getToolTipText();
                    message.setStatus(text);
                }
            }
            public void mouseExited(java.awt.event.MouseEvent e) {
                if ( e.getComponent() instanceof JComponent ) {
                    message.clearStatus();
                }
            }
        };
        showDate.addMouseListener(tooltipAdapter);
        showElapsed.addMouseListener(tooltipAdapter);
        showMem.addMouseListener(tooltipAdapter);
        
        
        frame.installStatusBar(statusBar);
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
// <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        
        jLabel1 = new javax.swing.JLabel();
        showDate = new javax.swing.JCheckBox();
        showMem = new javax.swing.JCheckBox();
        showElapsed = new javax.swing.JCheckBox();
        showDownload = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        
        setLayout(new java.awt.GridBagLayout());
        
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Status Bar Controls:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 8, 0, 0);
        add(jLabel1, gridBagConstraints);
        
        showDate.setSelected(true);
        showDate.setText("Clock");
        showDate.setToolTipText("Show clock component on the status bar.");
        showDate.setMaximumSize(new java.awt.Dimension(63, 23));
        showDate.setMinimumSize(new java.awt.Dimension(63, 23));
        showDate.setPreferredSize(new java.awt.Dimension(63, 23));
        showDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDateActionPerformed(evt);
            }
        });
        
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 8, 0, 0);
        add(showDate, gridBagConstraints);
        
        showMem.setSelected(true);
        showMem.setText("Memory");
        showMem.setToolTipText("Show JVM memory bar on status bar.");
        showMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMemActionPerformed(evt);
            }
        });
        showMem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                showMemMouseEntered(evt);
            }
        });
        
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 8, 0, 0);
        add(showMem, gridBagConstraints);
        
        showElapsed.setText("Elapsed");
        showElapsed.setToolTipText("Show an elapsed time counter.");
        showElapsed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showElapsedActionPerformed(evt);
            }
        });
        
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 8, 0, 0);
        add(showElapsed, gridBagConstraints);
        
        showDownload.setText("Download");
        showDownload.setToolTipText("Show an elapsed time counter.");
        showDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDownloadActionPerformed(evt);
            }
        });
        
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 8, 0, 0);
        add(showDownload, gridBagConstraints);
        
        jLabel3.setText("     ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(14, 0, 0, 0);
        add(jLabel3, gridBagConstraints);
        
        jLabel2.setText("     ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        add(jLabel2, gridBagConstraints);
        
    }
// </editor-fold>//GEN-END:initComponents
    
    private void showDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDownloadActionPerformed
        if ( showDownload.isSelected()) {
            download.getDisplayComponent().setVisible(true);
        } else {
            download.getDisplayComponent().setVisible(false);
        }
    }//GEN-LAST:event_showDownloadActionPerformed
    
    private void showMemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMemMouseEntered
        
    }//GEN-LAST:event_showMemMouseEntered
    
    private void showElapsedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showElapsedActionPerformed
        if ( showElapsed.isSelected()) {
            elapsedTime.getDisplayComponent().setVisible(true);
            elapsedTime.resetToZero();
            elapsedTime.startClock();
        } else {
            elapsedTime.getDisplayComponent().setVisible(false);
            elapsedTime.stopClock();
        }
        
    }//GEN-LAST:event_showElapsedActionPerformed
    
    private void showMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMemActionPerformed
        memory.getDisplayComponent().setVisible(showMem.isSelected());
        
    }//GEN-LAST:event_showMemActionPerformed
    
    private void showDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDateActionPerformed
        clock.getDisplayComponent().setVisible(showDate.isSelected());
        
    }//GEN-LAST:event_showDateActionPerformed
    
    
// Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JCheckBox showDate;
    private javax.swing.JCheckBox showDownload;
    private javax.swing.JCheckBox showElapsed;
    private javax.swing.JCheckBox showMem;
// End of variables declaration//GEN-END:variables
    
}
