package de.mt.jackrabbit.browser.ui;

import javax.swing.JFileChooser;
import javax.swing.JPanel;
import org.openide.util.NbBundle;

public final class ConnectVisualPanel1 extends JPanel {
    
  private String configFile;
  private String repoDir;
  

  /** Creates new form ConnectVisualPanel1 */
  public ConnectVisualPanel1() {
    initComponents();
  }

  @Override
  public String getName() {
    return NbBundle.getMessage(ConnectWizardPanel1.class, "Wizard-ChooseLocalRepo");
  }

  public String getConfigFile() {
    return tfConfiFile.getText();
  }

  public String getRepoDir() {
    return tfRepoDir.getText();
  }

  public String getUsername() {
    return tfUsername.getText();
  }

  public char[] getPassword() {
    return tfPassword.getPassword();
  }
  
  public void setEnabled(boolean bol) {
    super.setEnabled(bol);
    tfConfiFile.setEnabled(bol);
    tfPassword.setEnabled(bol);
    tfRepoDir.setEnabled(bol);
    tfUsername.setEnabled(bol);
    btSelectConfigFile.setEnabled(bol);
    btSelectRepoDir.setEnabled(bol);
  }
    
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    tfConfiFile = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    tfRepoDir = new javax.swing.JTextField();
    btSelectConfigFile = new javax.swing.JButton();
    btSelectRepoDir = new javax.swing.JButton();
    jLabel3 = new javax.swing.JLabel();
    tfUsername = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    tfPassword = new javax.swing.JPasswordField();

    tfConfiFile.setText("/home/markus/development/jackrabitt/jackrabit-test/repository.xml");

    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    org.openide.awt.Mnemonics.setLocalizedText(jLabel1, "Configfile");

    org.openide.awt.Mnemonics.setLocalizedText(jLabel2, "Repositorydirectory");

    tfRepoDir.setText("/home/markus/development/jackrabitt/jackrabit-test/repository");

    org.openide.awt.Mnemonics.setLocalizedText(btSelectConfigFile, "...");
    btSelectConfigFile.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btSelectConfigFileActionPerformed(evt);
      }
    });

    org.openide.awt.Mnemonics.setLocalizedText(btSelectRepoDir, "...");
    btSelectRepoDir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btSelectRepoDirActionPerformed(evt);
      }
    });

    org.openide.awt.Mnemonics.setLocalizedText(jLabel3, "Username");

    tfUsername.setText("username");

    org.openide.awt.Mnemonics.setLocalizedText(jLabel4, "Password");

    tfPassword.setText("password");

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
          .add(jLabel4)
          .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .add(jLabel3))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(layout.createSequentialGroup()
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
              .add(org.jdesktop.layout.GroupLayout.TRAILING, tfRepoDir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 219, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
              .add(org.jdesktop.layout.GroupLayout.TRAILING, tfConfiFile, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 219, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
              .add(btSelectRepoDir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
              .add(btSelectConfigFile, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
          .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
            .add(org.jdesktop.layout.GroupLayout.LEADING, tfPassword)
            .add(org.jdesktop.layout.GroupLayout.LEADING, tfUsername, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)))
        .add(33, 33, 33))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .add(59, 59, 59)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(tfConfiFile, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(btSelectConfigFile, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(jLabel1))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel2)
          .add(tfRepoDir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(btSelectRepoDir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .add(34, 34, 34)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel3)
          .add(tfUsername, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel4)
          .add(tfPassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(123, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void btSelectConfigFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelectConfigFileActionPerformed
    JFileChooser fileChooser = new JFileChooser();
    if (JFileChooser.APPROVE_OPTION == fileChooser.showOpenDialog(this)) {
        tfConfiFile.setText(fileChooser.getSelectedFile().getAbsolutePath());
    }
}//GEN-LAST:event_btSelectConfigFileActionPerformed

  private void btSelectRepoDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelectRepoDirActionPerformed
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    if (JFileChooser.APPROVE_OPTION == fileChooser.showOpenDialog(this)) {
        tfRepoDir.setText(fileChooser.getSelectedFile().getAbsolutePath());
    }
  }//GEN-LAST:event_btSelectRepoDirActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btSelectConfigFile;
  private javax.swing.JButton btSelectRepoDir;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JTextField tfConfiFile;
  private javax.swing.JPasswordField tfPassword;
  private javax.swing.JTextField tfRepoDir;
  private javax.swing.JTextField tfUsername;
  // End of variables declaration//GEN-END:variables

}

