/*
 * ClickableListExample.java
 *
 * Created on 5 de enero de 2007, 19:25
 */

package org.jdesktop.swingx.clickablelist;

import com.jgoodies.looks.LookUtils;
import com.jgoodies.looks.Options;
import com.jgoodies.looks.plastic.PlasticXPLookAndFeel;
import com.jgoodies.looks.plastic.theme.DesertBlue;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.UIManager;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author  dags
 */
public class ClickableListExample extends org.jdesktop.swingx.JXFrame implements ClickableListListener, ListSelectionListener {
    
    /** Creates new form BeanForm */
    public ClickableListExample() {
        initComponents();
        
        ClickableListModel modelo = new ClickableListModel();
        
        // add some items to model ...
        for (int i = 1; i < 50; i++) {
            modelo.addElement(new ClickableListElement(i, "Item " + i));
        }
        
        clickableList1.setModel(modelo);
        clickableList1.addClickableListListener(this);
        clickableList1.getSelectionModel().addListSelectionListener(this);
        pack();
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jXTitledSeparator1 = new org.jdesktop.swingx.JXTitledSeparator();
        clickableList1 = new org.jdesktop.swingx.clickablelist.ClickableList();
        jXTitledSeparator2 = new org.jdesktop.swingx.JXTitledSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jXList1 = new org.jdesktop.swingx.JXList();
        jXTitledSeparator3 = new org.jdesktop.swingx.JXTitledSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jXList2 = new org.jdesktop.swingx.JXList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jXTitledSeparator1.setTitle("ClickableList");

        jXTitledSeparator2.setTitle("Checked Items");

        jScrollPane1.setViewportView(jXList1);

        jXTitledSeparator3.setTitle("Selected Items");

        jScrollPane2.setViewportView(jXList2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXTitledSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addComponent(clickableList1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXTitledSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXTitledSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXTitledSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXTitledSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXTitledSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(clickableList1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.clickablelist.ClickableList clickableList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXList jXList1;
    private org.jdesktop.swingx.JXList jXList2;
    private org.jdesktop.swingx.JXTitledSeparator jXTitledSeparator1;
    private org.jdesktop.swingx.JXTitledSeparator jXTitledSeparator2;
    private org.jdesktop.swingx.JXTitledSeparator jXTitledSeparator3;
    // End of variables declaration//GEN-END:variables
    
    public static void main(String[] args) throws Exception {
        
        UIManager.put("ClassLoader", LookUtils.class.getClassLoader());
        
        //init GUI
        Options.setDefaultIconSize(new Dimension(16, 16));
        
        // Set font options
        UIManager.put(Options.USE_SYSTEM_FONTS_APP_KEY,Boolean.TRUE);
        
        Options.setTabIconsEnabled(true);
        UIManager.put(Options.TAB_ICONS_ENABLED_KEY, Boolean.TRUE);
        
//        Options.setGlobalFontSizeHints(FontSizeHints.MIXED);
        Options.setUseNarrowButtons(false);
//        Options.setUseSystemFonts(true);
        
        // Global options
        Options.setPopupDropShadowEnabled(true);
        UIManager.put(Options.POPUP_DROP_SHADOW_ENABLED_KEY,Boolean.TRUE);
        
        try {
            PlasticXPLookAndFeel.setTabStyle(PlasticXPLookAndFeel.TAB_STYLE_METAL_VALUE);
            PlasticXPLookAndFeel.setTabStyle("Metal");
            PlasticXPLookAndFeel.setHighContrastFocusColorsEnabled(true);
            PlasticXPLookAndFeel.setPlasticTheme(new DesertBlue());
            UIManager.setLookAndFeel(new PlasticXPLookAndFeel());
        } catch (Exception e) {
            System.err.println("An error occured while initialising UI : " + e);
        }
        
        ClickableListExample example = new ClickableListExample();
        example.setVisible(true);
        
    }
    
    // this is to test the ClicbableListListener
    public void ClickableListChanged(ClickableList l) {
        
        ArrayList l2 = l.getClickedObjects();
        DefaultListModel model2 = new DefaultListModel();
        
        for (int j = 0; j < l2.size(); j++)
            model2.addElement(l2.get(j));
        
        jXList1.setModel(model2);
        
    }
    
    public void valueChanged(ListSelectionEvent e) {
        
        if (e.getValueIsAdjusting() == true) return;
        
        Object[] l3 = clickableList1.getSelectedObjects();
        
        DefaultListModel model3 = new DefaultListModel();
        
        for (int j = 0; j < l3.length; j++)
            model3.addElement(l3[j]);
        
        jXList2.setModel(model3);
    }
}
