// ============================================================================
// $Id: UncheckedParseException.java 620 2005-08-19 22:38:33Z david_hall $
// Copyright (c) 2004  David A. Hall
// ============================================================================
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
// ============================================================================

package org.jdesktop.jdnc.swingel;

/**
 * Unchecked version of ParseException, generated by the static evaluation
 * methods.  The only cause that can be carried is a ParseException.
 */

public class UncheckedParseException extends RuntimeException {

  public UncheckedParseException(ParseException x) { super(x); }

  public UncheckedParseException() { super(); }

  public UncheckedParseException(String message) { super(message); }

  public UncheckedParseException(String message, ParseException x) { super(x); }
}
