import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/*
 * TestFrame.java
 *
 * Created on 12 de Janeiro de 2007, 20:39
 */

/**
 *
 * @author  Mário César
 */
public class TestFrame extends javax.swing.JFrame {
    
    /**
     * Creates new form TestFrame
     */
    public TestFrame() {
        initComponents();
        jEditorPane1.setText("<html>This button lists everything that I haven't done yet on the JXSplitButton project. This button really is a good example of how JXSplitButton works, but it will work really lake a \"ToDo-List\" too, because I'm going to update it every time that I update the JXSplitButton.</html>");
        jEditorPane1.setCaretPosition(0);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPopupMenuHelp = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPopupMenuActions = new javax.swing.JPopupMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jPopupMenuToDoList = new javax.swing.JPopupMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        jXSplitButton1 = new JXSplitButton();
        jSeparator03 = new javax.swing.JSeparator();
        jXSplitButton2 = new JXSplitButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaEdit = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jXSplitButton3 = new JXSplitButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();

        jPopupMenuHelp.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
                jPopupMenuHelpPopupMenuCanceled(evt);
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jPopupMenuHelpPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jPopupMenuHelpPopupMenuWillBecomeVisible(evt);
            }
        });

        jMenuItem1.setText("Help");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });

        jPopupMenuHelp.add(jMenuItem1);

        jMenuItem2.setText("About");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });

        jPopupMenuHelp.add(jMenuItem2);

        jMenuItem3.setText("New");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });

        jPopupMenuActions.add(jMenuItem3);

        jMenuItem4.setText("Save");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });

        jPopupMenuActions.add(jMenuItem4);

        jPopupMenuActions.add(jSeparator1);

        jMenuItem5.setText("Exit");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });

        jPopupMenuActions.add(jMenuItem5);

        jMenuItem6.setText("Create all UI delegates");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });

        jPopupMenuToDoList.add(jMenuItem6);

        jMenuItem7.setText("Arrow icon generation");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });

        jPopupMenuToDoList.add(jMenuItem7);

        jMenuItem8.setText("How to show drop-down menu");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });

        jPopupMenuToDoList.add(jMenuItem8);

        jMenuItem9.setText("Clicks on arrow icon with no drop-down menu setted");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });

        jPopupMenuToDoList.add(jMenuItem9);

        jMenuItem10.setText("What happened when drop-down is showed");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });

        jPopupMenuToDoList.add(jMenuItem10);

        jMenuItem11.setText("Even more");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });

        jPopupMenuToDoList.add(jMenuItem11);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JXSplitButton Demo");
        jToolBar1.setRollover(true);
        jXSplitButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New.gif")));
        jXSplitButton1.setText("New");
        jXSplitButton1.setDropDownMenu(jPopupMenuActions);
        jToolBar1.add(jXSplitButton1);

        jSeparator03.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator03.setMaximumSize(new java.awt.Dimension(2, 25));
        jSeparator03.setMinimumSize(new java.awt.Dimension(2, 25));
        jSeparator03.setPreferredSize(new java.awt.Dimension(2, 25));
        jToolBar1.add(jSeparator03);

        jXSplitButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Help.gif")));
        jXSplitButton2.setDropDownMenu(jPopupMenuHelp);
        jToolBar1.add(jXSplitButton2);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.NORTH);

        jTextAreaEdit.setColumns(20);
        jTextAreaEdit.setRows(5);
        jScrollPane1.setViewportView(jTextAreaEdit);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setPreferredSize(new java.awt.Dimension(100, 80));
        jXSplitButton3.setText("ToDo-List");
        jXSplitButton3.setDropDownMenu(jPopupMenuToDoList);
        jXSplitButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXSplitButton3ActionPerformed(evt);
            }
        });

        jEditorPane1.setEditable(false);
        jEditorPane1.setContentType("text/html");
        jEditorPane1.setFocusCycleRoot(false);
        jScrollPane2.setViewportView(jEditorPane1);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jXSplitButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .add(jXSplitButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-396)/2, (screenSize.height-297)/2, 396, 297);
    }// </editor-fold>//GEN-END:initComponents

    private void jPopupMenuHelpPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jPopupMenuHelpPopupMenuWillBecomeVisible
// TODO add your handling code here:
    }//GEN-LAST:event_jPopupMenuHelpPopupMenuWillBecomeVisible

    private void jPopupMenuHelpPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jPopupMenuHelpPopupMenuWillBecomeInvisible
// TODO add your handling code here:
    }//GEN-LAST:event_jPopupMenuHelpPopupMenuWillBecomeInvisible

    private void jPopupMenuHelpPopupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jPopupMenuHelpPopupMenuCanceled
// TODO add your handling code here:
    }//GEN-LAST:event_jPopupMenuHelpPopupMenuCanceled

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "There should be others things that I didn't put in that list.\nAnd of course there must be bug corrections and so on.\n\nBut, for now, I want to ask: any suggestions?! :^)", "Even more...", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Must be the entire button selected? Or just put a lowered border on the arrow icon?\nWell, I was selecting entire component, now I'm just putting a lowered border on the arrow icon's JLabel.\nOk, but... Will happened always the same, don't matter the LAF?\nI think that it should be more discussed and tested in other language's implementations.", "What happened when drop-down is showed?", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "What happened when user clicks on the JXSplitButton's arrow icon and there's no drop-down menu setted?\nFor now I'm just firing actionPerformed. But, is it the correct way?", "Clicks on arrow icon with no drop-down menu setted", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "There's a problem about the position where the drop-down menu is showed. The thing is that there's a empty space on the JButton's bottom on some LAFs.\nFor example, if I just use:\n\ndropDownMenu.show(this, 0, this.getHeight());\n\nIt will fail on WindowsXP LAF, because there's a one pixel empty line on the JButton's bottom. And I really don't know in others LAFs, especially on custom LAFs.", "Show drop-down menu on UI delegate", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Doing it, we can have diferent arrow icons for diferent LAFs. For example, we could draw it like the JComboBox's arrow icon in each LAF.", "Arrow icon generation code on UI delegate", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "It's important because then many problems could be easily solved, for example:\n\n* Diferent arrow icons for diferent LAFs;\n* The y position where the drop-down menu is showed (the JButton has empty space on the height);\n* Etc.", "Create all UI delegates", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jXSplitButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXSplitButton3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Thing that I haven't done yet:\n\n* Create all UI delegates, extending the buttonUI delegates existents (WindowsButtonUI, MetalButtonUI, etc.);\n* Put the icon generation code on UI delegate;\n* Put the method that shows the drop-down menu on UI delegate;\n* Decide what happened when the user click on the arrow icon and there's no drop-down menu setted;\n* Decide what happened when the drop-down is showed: Entire button selected? Just a border on the arrow icon? Etc.;\n* Other things that I didn't remembered for now and suggestions, bug corrections, etc.", "ToDo-List", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jXSplitButton3ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        jTextAreaEdit.setText("");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Not implemented. Sorry.\nHow about using Notepad to it?! ;^)P", "Save", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "What exactly do you whant? It's just a demo!.", "Help", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "That's just an example of the new JXSplitButton component.\nBy Mario Cesar.", "About", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(
                            UIManager.getSystemLookAndFeelClassName());
                } catch (Exception e) {
                    System.err.println("Couldn't get specified look and feel, for some reason.");
                    System.err.println("Using the default look and feel.");
                    e.printStackTrace();
                }
                TestFrame frame = new TestFrame();
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenuActions;
    private javax.swing.JPopupMenu jPopupMenuHelp;
    private javax.swing.JPopupMenu jPopupMenuToDoList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator03;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextAreaEdit;
    private javax.swing.JToolBar jToolBar1;
    private JXSplitButton jXSplitButton1;
    private JXSplitButton jXSplitButton2;
    private JXSplitButton jXSplitButton3;
    // End of variables declaration//GEN-END:variables
    
}