import javax.swing.JOptionPane;
import javax.swing.UIManager;
/*
 * TestFrame.java
 *
 * Created on 15 de Janeiro de 2007, 19:34
 */

/**
 *
 * @author  Mário César
 */
public class TestFrame extends javax.swing.JFrame {
    private String[] gDirections = {"TOP_TO_BOTTOM", "BOTTOM_TO_TOP",
                                           "RIGHT_TO_LEFT", "LEFT_TO_RIGHT"};
    private int[] gDirectionValues = {JXLabel.TOP_TO_BOTTOM,
                                      JXLabel.BOTTOM_TO_TOP,
                                      JXLabel.RIGHT_TO_LEFT,
                                      JXLabel.LEFT_TO_RIGHT};
    private String[] bRenderMethods = {"GRADIENT",
                                       "BACKGROUND_COLOR",
                                       "TILED_IMAGE"};
    private int[] bRenderMethodValues = {JXLabel.GRADIENT,
                                         JXLabel.BACKGROUND_COLOR,
                                         JXLabel.TILED_IMAGE};
    private String[] tOrientation = {"NORMAL", "INVERTED",
                                     "VERTICAL_LEFT", "VERTICAL_RIGHT"};
    private int[] tOrientationValues = {JXLabel.NORMAL, JXLabel.INVERTED,
                                        JXLabel.VERTICAL_LEFT, JXLabel.VERTICAL_RIGHT};
    private String[] hAlignments = {"LEADING", "LEFT", "CENTER", "RIGHT", "TRAILING"};
    private int[] hAlignmentValues = {JXLabel.LEADING, JXLabel.LEFT,
                                      JXLabel.CENTER, JXLabel.RIGHT,
                                      JXLabel.TRAILING};
    private String[] vAlignments = {"CENTER", "TOP", "BOTTOM"};
    private int[] vAlignmentValues = {JXLabel.CENTER, JXLabel.TOP, JXLabel.BOTTOM};
    /**
     * Creates new form TestFrame
     */
    public TestFrame() {
        initComponents();
        jTextFieldText.setText(jXLabel1.getText());
        int i;
        for (i = 0; i < bRenderMethods.length; i++) {
            jComboBoxBackgroundRender.addItem(bRenderMethods[i]);
        }
        for (i = 0; i < gDirections.length; i++) {
            jComboBoxGradientDirection.addItem(gDirections[i]);
        }
        for (i = 0; i < hAlignments.length; i++) {
            jComboBoxHorizontalAlignment.addItem(hAlignments[i]);
        }
        for (i = 0; i < tOrientation.length; i++) {
            jComboBoxTextOrientation.addItem(tOrientation[i]);
        }
        for (i = 0; i < vAlignments.length; i++) {
            jComboBoxVerticalAlignment.addItem(vAlignments[i]);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jXLabel1 = new JXLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelText = new javax.swing.JLabel();
        jLabelTextOrientation = new javax.swing.JLabel();
        jLabelHorizontalAlignment = new javax.swing.JLabel();
        jLabelVerticalAlignment = new javax.swing.JLabel();
        jLabelBackgroundRender = new javax.swing.JLabel();
        jTextFieldText = new javax.swing.JTextField();
        jComboBoxTextOrientation = new javax.swing.JComboBox();
        jComboBoxHorizontalAlignment = new javax.swing.JComboBox();
        jComboBoxVerticalAlignment = new javax.swing.JComboBox();
        jComboBoxBackgroundRender = new javax.swing.JComboBox();
        jLabelGradientDirection = new javax.swing.JLabel();
        jComboBoxGradientDirection = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jXLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jXLabel1.setText("jXLabel1");
        jXLabel1.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/yllw024.gif")));
        jXLabel1.setFont(new java.awt.Font("Verdana", 1, 12));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelText.setText("Text:");

        jLabelTextOrientation.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTextOrientation.setText("TextOrientation:");

        jLabelHorizontalAlignment.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelHorizontalAlignment.setText("HorizontalAlignment:");

        jLabelVerticalAlignment.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelVerticalAlignment.setText("VerticalAlignment:");

        jLabelBackgroundRender.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelBackgroundRender.setText("BackgroundRender:");

        jTextFieldText.setText("jTextField1");
        jTextFieldText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldTextKeyReleased(evt);
            }
        });

        jComboBoxTextOrientation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTextOrientationActionPerformed(evt);
            }
        });

        jComboBoxHorizontalAlignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxHorizontalAlignmentActionPerformed(evt);
            }
        });

        jComboBoxVerticalAlignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxVerticalAlignmentActionPerformed(evt);
            }
        });

        jComboBoxBackgroundRender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBackgroundRenderActionPerformed(evt);
            }
        });

        jLabelGradientDirection.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelGradientDirection.setText("GradientDirection:");

        jComboBoxGradientDirection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGradientDirectionActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabelGradientDirection, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabelBackgroundRender, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabelVerticalAlignment, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabelText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabelTextOrientation, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabelHorizontalAlignment, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jComboBoxTextOrientation, 0, 253, Short.MAX_VALUE)
                    .add(jTextFieldText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .add(jComboBoxHorizontalAlignment, 0, 253, Short.MAX_VALUE)
                    .add(jComboBoxVerticalAlignment, 0, 253, Short.MAX_VALUE)
                    .add(jComboBoxBackgroundRender, 0, 253, Short.MAX_VALUE)
                    .add(jComboBoxGradientDirection, 0, 253, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelText)
                    .add(jTextFieldText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelTextOrientation)
                    .add(jComboBoxTextOrientation, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelHorizontalAlignment)
                    .add(jComboBoxHorizontalAlignment, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelVerticalAlignment)
                    .add(jComboBoxVerticalAlignment, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelBackgroundRender)
                    .add(jComboBoxBackgroundRender, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelGradientDirection)
                    .add(jComboBoxGradientDirection, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jXLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jXLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxGradientDirectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGradientDirectionActionPerformed
        // TODO add your handling code here:
        String selected = jComboBoxGradientDirection.getSelectedItem().toString();
        for (int i = 0; i < gDirections.length; i++) {
            if (gDirections[i].equals(selected)) {
                jXLabel1.setGradientDirection(gDirectionValues[i]);
                return;
            }
        }
    }//GEN-LAST:event_jComboBoxGradientDirectionActionPerformed

    private void jComboBoxBackgroundRenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBackgroundRenderActionPerformed
        // TODO add your handling code here:
        String selected = jComboBoxBackgroundRender.getSelectedItem().toString();
        for (int i = 0; i < bRenderMethods.length; i++) {
            if (bRenderMethods[i].equals(selected)) {
                jXLabel1.setRenderBackground(bRenderMethodValues[i]);
                return;
            }
        }
    }//GEN-LAST:event_jComboBoxBackgroundRenderActionPerformed

    private void jComboBoxVerticalAlignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxVerticalAlignmentActionPerformed
        // TODO add your handling code here:
        String selected = jComboBoxVerticalAlignment.getSelectedItem().toString();
        for (int i = 0; i < vAlignments.length; i++) {
            if (vAlignments[i].equals(selected)) {
                jXLabel1.setVerticalAlignment(vAlignmentValues[i]);
                return;
            }
        }
    }//GEN-LAST:event_jComboBoxVerticalAlignmentActionPerformed

    private void jComboBoxHorizontalAlignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxHorizontalAlignmentActionPerformed
        // TODO add your handling code here:
        String selected = jComboBoxHorizontalAlignment.getSelectedItem().toString();
        for (int i = 0; i < hAlignments.length; i++) {
            if (hAlignments[i].equals(selected)) {
                jXLabel1.setHorizontalAlignment(hAlignmentValues[i]);
                return;
            }
        }
    }//GEN-LAST:event_jComboBoxHorizontalAlignmentActionPerformed

    private void jComboBoxTextOrientationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTextOrientationActionPerformed
        // TODO add your handling code here:
        String selected = jComboBoxTextOrientation.getSelectedItem().toString();
        for (int i = 0; i < tOrientation.length; i++) {
            if (tOrientation[i].equals(selected)) {
                jXLabel1.setTextOrientation(tOrientationValues[i]);
                return;
            }
        }
    }//GEN-LAST:event_jComboBoxTextOrientationActionPerformed

    private void jTextFieldTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTextKeyReleased
        // TODO add your handling code here:
        jXLabel1.setText(jTextFieldText.getText());
    }//GEN-LAST:event_jTextFieldTextKeyReleased
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(
                            UIManager.getSystemLookAndFeelClassName());
                } catch (Exception e) {
                    System.err.println("Couldn't get specified look and feel, for some reason.");
                    System.err.println("Using the default look and feel.");
                    e.printStackTrace();
                }
                TestFrame test = new TestFrame();
                test.setLocationRelativeTo(null);
                test.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxBackgroundRender;
    private javax.swing.JComboBox jComboBoxGradientDirection;
    private javax.swing.JComboBox jComboBoxHorizontalAlignment;
    private javax.swing.JComboBox jComboBoxTextOrientation;
    private javax.swing.JComboBox jComboBoxVerticalAlignment;
    private javax.swing.JLabel jLabelBackgroundRender;
    private javax.swing.JLabel jLabelGradientDirection;
    private javax.swing.JLabel jLabelHorizontalAlignment;
    private javax.swing.JLabel jLabelText;
    private javax.swing.JLabel jLabelTextOrientation;
    private javax.swing.JLabel jLabelVerticalAlignment;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldText;
    private JXLabel jXLabel1;
    // End of variables declaration//GEN-END:variables
    
}
