/*
 * $Id: JXSummaryTableDemo.java 1371 2007-06-04 12:34:18Z rasto1968 $
 *
 * Copyright 2006 Sun Microsystems, Inc., 4150 Network Circle,
 * Santa Clara, California 95054, U.S.A. All rights reserved.
 */
package org.jdesktop.swingx.demo;

import java.awt.BorderLayout;
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.JXSummaryTable;
import org.jdesktop.swingx.decorator.Highlighter;
import org.jdesktop.swingx.decorator.HighlighterFactory;

/**
 * Demonstrates the use of JXSummaryTable.
 * @author Rob Stone
 */
public class JXSummaryTableDemo extends JFrame {
    public JXSummaryTableDemo() {
        initComponents();
        
        /*
         * JXSummaryTable behaves exactly like a JXTable, there are no API. It
         * will always display the last row of data at the bottom of the table
         * regardless of sorting.
         */
        JXSummaryTable jXSummaryTable=new JXSummaryTable(new DefaultTableModel(
            new Object [][] {
                {"Row 1", 1, 2, 3, 4},
                {"Row 2", 5, 6, 7, 8},
                {"Row 3", 9, 10, 11, 12},
                {"Total", 15, 18, 21, 24}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jXSummaryTable.setColumnControlVisible(true);
        jXSummaryTable.setHighlighters(new Highlighter[] {HighlighterFactory.createSimpleStriping(HighlighterFactory.GENERIC_GRAY)});
        jScrollPane1.setViewportView(jXSummaryTable);
        pack();        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        jScrollPane1 = new JScrollPane();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(jScrollPane1, BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JXSummaryTableDemo().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
