/*
 * DemoFrame.java
 *
 * Created on 28 de Junho de 2005, 10:51
 */

package org.jdesktop.jdnc.incubator.rlopes.jdncutils.demo;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.LineNumberReader;
import java.util.Vector;
import javax.swing.AbstractAction;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.jdnc.incubator.rlopes.jdncutils.*;

/**
 *
 * @author  Ricardo Lopes
 */
public class DemoFrame extends javax.swing.JFrame {
    
    /**
     * Creates new form DemoFrame 
     */
    public DemoFrame() {
        initComponents();
        customizeTable();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
// <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jNTable1 = new org.jdesktop.jdnc.JNTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jButton1.setText("Show filter panel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent event) {
                jButton1ActionPerformed(event);
            }
        });
        
        jPanel3.add(jButton1);
        
        getContentPane().add(jPanel3, java.awt.BorderLayout.NORTH);
        
        jNTable1.setPreferredSize(new java.awt.Dimension(450, 250));
        getContentPane().add(jNTable1, java.awt.BorderLayout.CENTER);
        
        jTextArea1.setColumns(35);
        jTextArea1.setEditable(false);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(20);
        jTextArea1.setText("Control + F anywhere or by pressing the search button the filter panel appears on the bottom of the table and the focus goes to the textfield.\n\nESC on the filter panel removes the filter panel.\n\nIn this example the filtering is done with the values of the second column.\n\nThe position of the filter panel can be at the TOP or the BOTTOM of the JNTable.\n");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);
        
        getContentPane().add(jScrollPane1, java.awt.BorderLayout.EAST);
        
        pack();
    }
// </editor-fold>//GEN-END:initComponents

    protected void customizeTable() {        
        // on CONTROL + F (anywhere) hook the filter panel
        InputMap inputMap = jNTable1.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        String actionMapKey = "showFilterPanel";
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F, KeyEvent.CTRL_DOWN_MASK), actionMapKey);
        jNTable1.getActionMap().put(actionMapKey, new AbstractAction(actionMapKey) {        
            public void actionPerformed(ActionEvent event) {
                JDNCUtils.hookFilterPanel(jNTable1, SwingConstants.BOTTOM, 1);
            }
        });        
        
        Vector<Vector<String>> dataVector = new Vector<Vector<String>>();
        LineNumberReader reader = new LineNumberReader(new BufferedReader(new InputStreamReader(getClass().getResourceAsStream("/org/jdesktop/jdnc/incubator/rlopes/jdncutils/demo/data.csv"))));
        String line;
        try {
            while ((line = reader.readLine()) != null) {
                Vector item = new Vector();            
                item.add(reader.getLineNumber());
                item.add(line);
                dataVector.add(item);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        Vector columns = new Vector();
        columns.add("Line");
        columns.add("Name");
        jNTable1.setModel(new DefaultTableModel(dataVector, columns));
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent event) {//GEN-FIRST:event_jButton1ActionPerformed
        JDNCUtils.hookFilterPanel(jNTable1, SwingConstants.BOTTOM, 1);
    }//GEN-LAST:event_jButton1ActionPerformed
       
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DemoFrame().setVisible(true);
            }
        });
    }
    
// Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private org.jdesktop.jdnc.JNTable jNTable1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
// End of variables declaration//GEN-END:variables
    
}

